#!/bin/bash


# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            30

# Set decoration colors
berryc focus_color         191724
berryc unfocus_color       191725
berryc inner_focus_color   EBBCBA
berryc inner_unfocus_color 6E6A86
berryc text_focus_color    ffffff
berryc text_unfocus_color  E0DEF4

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "CaskaydiaCove Nerd Font Mono"
